In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
def rembourage(X, pad):
    return np.pad(X, pad_width=pad, mode='constant', constant_values=0)

In [4]:
arr = np.ones((3, 3))
rembourage(arr, 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
test_arr = np.zeros((5, 5))
test_arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
test_arr[1, 1] = 1
test_arr[3, 3] = 1

In [7]:
test_arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
for i in range(1, 4):
    for j in range(1, 4):
        test_arr[i, j] = 1

In [9]:
test_arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
def rembourage2(X, pad):
    new_mat = np.zeros((X.shape[0] + pad*2, X.shape[1] + pad*2))
    for i in range(len(X)):
        for j in range(len(X[0])):
            new_mat[i + pad, j + pad] = X[i, j]

    return new_mat

In [25]:
arr = np.ones((3, 3))
rembourage2(arr, 1)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])